// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBB67GSUSWPXrao49xTS4kWFqapujOpfDg",
      authDomain: "pentspace-6e357.firebaseapp.com",
      projectId: "pentspace-6e357",
      storageBucket: "pentspace-6e357.appspot.com",
      messagingSenderId: "328276182948",
      appId: "1:328276182948:web:168560d30043dd0b432331",
      measurementId: "G-Y9VJ7BE7PB");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCido95Hmtnm1A4DjX_LbuVNvIR4b4r7NU',
    appId: '1:328276182948:ios:a972695bdc3bcd67432331',
    messagingSenderId: '328276182948',
    projectId: 'pentspace-6e357',
    storageBucket: 'pentspace-6e357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCido95Hmtnm1A4DjX_LbuVNvIR4b4r7NU',
    appId: '1:328276182948:ios:a972695bdc3bcd67432331',
    messagingSenderId: '328276182948',
    projectId: 'pentspace-6e357',
    storageBucket: 'pentspace-6e357.appspot.com',
    iosBundleId: 'com.pentspace.theapptitude',
  );
}
